
/*
 * CORBA interfaces for Dyna. Prefixes 'C' and 'IC' are used to avoid confusion
 * with plain Java version.
 */

module com {
module dawidweiss {
module dyna {
module corba {
module bindings {

	/*
	 * Forward references and typedefs.
	 */
	
	interface ICGameServer;
	interface ICGameListener;
	interface ICGame;
	interface ICPlayerController;

	struct CPlayer;
	struct CPlayerState;
	struct CStanding;
	struct CControllerState;

    /*
     * Cels are int-coded.
     * <pre>
     * 0x007f - The int-ordinal of CellType
     * 0xff80 - Cell counter associated with the cell.
     * </pre> 
     */
    typedef sequence<short> CCellSeq;

	typedef sequence<CPlayer> CPlayerSeq;
    typedef sequence<CPlayerState> CPlayerStateSeq;
    typedef sequence<CStanding> CStandingSeq;

	/**
	 * A player is described with a name and unique id.
	 */
	struct CPlayer {
	    long id;
	    wstring name;
	};

	/*
	 * Basic data types.
	 */
    struct CDimension {
       long width, height;
    };

    struct CPoint {
       long x, y;
    };
	
	/*
	 * Game events. Propagated by value as a union of structures corresponding
	 * to Java event types.
	 */

	struct CPlayerState {
	   long animationFrame;
	   long animationState;
	   CPoint position;
	};

	struct CBoardInfo {
	   CDimension gridSize;
	   long cellSize;
	   CDimension pixelSize;
	};	 

	enum CGameEventType {
		GAME_STATE, SOUND_EFFECT, GAME_START
	};
	
	struct CGameState {
	   CCellSeq cells;
	   CPlayerStateSeq players;
	};
	
	struct CGameStart {
	   CBoardInfo boardInfo;
	};
	
	enum CSoundEffectType {
	    BOMB, BONUS, DYING
	};

	struct CSoundEffect {
		CSoundEffectType effect;
		long count;
	};

	union CGameEvent switch (CGameEventType) {
		case GAME_STATE:
			CGameState gameState;
		case SOUND_EFFECT:
			CSoundEffect soundEffect;
	    case GAME_START:
	        CGameStart gameStart;
	};
	typedef sequence<CGameEvent> CGameEventSeq; 

    /**
     * Standings after game over.
     */
    struct CStanding {
        long id;
        long victimNumber;
    };

	/*
	 * Controller structures.
	 */

    enum CDirection
    {
        LEFT, RIGHT, UP, DOWN, NONE
    };

	struct CControllerState {
	   CDirection direction;
	   boolean dropsBomb;
	};

	/**
	 * A game server is the main object on which players are registered and games are 
	 * started. 
	 */
	interface ICGameServer {
	    /** Register a new player in the controller. */
	    CPlayer register(in wstring name, in ICPlayerController controller);

	    /** Create a game for a set of players. */
	    ICGame create(in long boardNumber, in CPlayerSeq players);

	    /** Currently registered players. */
	    CPlayerSeq players();
	};

	/**
	 * A single game between a set of players.
	 */
	interface ICGame {
	    /**
	     * Starts the game and executes the entire game loop.
	     */
	    void run();

        /** Add an extra game listener. */
	    void add(in ICGameListener listener);

        /** Remove an extra game listener. */
	    void remove(in ICGameListener listener);
	};

	/**
	 * A game listener receives events from one or more games.
	 */
	interface ICGameListener {
	   /**
	    * The game is about to start.
	    */
	   void onStart(in CBoardInfo boardInfo, in CPlayerSeq players);

	   /**
	    * An asynchronous callback received on each game frame (some frames may be skipped
	    * if the connection is slow). 
	    */
	   oneway void onFrame(in long frame, in CGameEventSeq events);

	   /**
	    * Game over event.
	    */
	   void onEnd(in CPlayer winner, in CStandingSeq standings);
	};
	
	/**
	 * Game controller expects player control signals to be passed via this interface.
	 */ 
	interface ICControllerCallback {
        /**
         * This is a synchronous call, so conserve the resources of your client
         * and avoid sending spurious messages.
         */
        void update(in CControllerState state);
	};

	/**
	 * A controller for a single remote player.
	 */
    interface ICPlayerController : ICGameListener {
        /**
         * Invoked by the game controller just before the game starts. The 
         * player's controller should pass state information to the provided callback
         * object and <b>must not</b> flood it with requests. It is advised to have
         * one call every time the state needs to be changed.
         */  
        void onControllerSetup(in ICControllerCallback callback); 
    };
};
};
};
};
};